# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies
      
      # Build do angular
      - run: npm run-script build

      - save_cache:
          paths:
            - dist
            - firebase.json
            - .firebaserc
          key: v1-last-deploy

      # Zip do conteúdo gerado
      - run: cd dist/web-app && zip -r frontend-1.0.0-${CIRCLE_BUILD_NUM}.zip .

      # Movendo o zip para um diretório de deploy
      - run: mkdir deploy && mv dist/web-app/*.zip deploy

      - store_artifacts:
          path: deploy
  deploy:

    docker:
      - image: circleci/node:10
    
    working_directory: ~/repo
    
    steps:
      # Restaura o cache das dependências
      - restore_cache:
          keys:
            - v1-dependencies
      
      # Restaura o cache da build
      - restore_cache:
          keys:
            - v1-last-deploy

      # Realiza o deploy no Firebase
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  frontend_build:
    jobs: 
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master